# Generated by Django 2.1.1 on 2018-09-18 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=48)),
                ('author', models.CharField(max_length=48)),
                ('status', models.CharField(choices=[('available', 'Available'), ('checked-out', 'Checked-Out')], default='available', max_length=48)),
            ],
        ),
    ]
