# Generated by Django 2.1.1 on 2018-09-19 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lender_books', '0002_remove_book_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover_image',
            field=models.FileField(default=1, upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
