# Generated by Django 2.1.1 on 2018-09-19 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lender_books', '0002_auto_20180919_0313'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover_image',
            field=models.FileField(default='None', upload_to='static'),
            preserve_default=False,
        ),
    ]
