# Generated by Django 2.1.1 on 2018-09-19 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lender_books', '0003_book_cover_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='cover_image',
        ),
    ]
