# Generated by Django 2.1.1 on 2018-09-20 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lender_books', '0004_remove_book_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
