# Generated by Django 2.1.1 on 2018-09-21 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lender_books', '0006_auto_20180920_2139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='',
        ),
        migrations.AddField(
            model_name='book',
            name='year',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
